# Exports parts of the file generated by busplot.py to a CSV
# so it can be easily viewed and analyzed in Excel.

import json

def parseFile():
    f = open('buses.txt','r')
    o = open('busNumberData.txt','w')

    line = f.readline()
    while(line != ""):
        blues = 0
        reds = 0
        yellows = 0
        greens = 0
        try:
            record = json.loads(line)
            for bus in record["data"]:
                print(json.dumps(bus))
                if bus["color"] == "blue":
                    blues+=1
                elif bus["color"] == "red":
                    reds+=1
                elif bus["color"] == "yellow":
                    yellows+=1
                elif bus["color"] == "green": 
                    greens+=1 
                
            o.write(str(record["time"]) + "," + str(reds) + "," + str(blues) + "," + str(yellows) + "," + str(greens)+"\n") 
        except IOError:
            print("Error.")
        except ValueError:
            print("Value error")

        line = f.readline()

    f.close()
    o.close()


parseFile()
